const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>new Intl.NumberFormat('ar-IQ').format(Math.round(n))+' د.ع';
let products=[['لاتيه عراقي',4500,'إسبريسو وحليب مخملي','☕','قهوة'],['كابتشينو',4500,'رغوة خفيفة وطعم قوي','☕','قهوة'],['أمريكانو',3500,'قهوة سوداء مضبوطة','☕','قهوة'],['موكا بارد',5500,'شوكولاتة وكريمة','🥤','بارد'],['سبانيش لاتيه',5500,'حليب محلى وكراميل','☕','قهوة'],['ماتشا',6000,'ماتشا ياباني وحليب','🍵','بارد'],['كرواسون زبدة',3000,'مخبوز اليوم','🥐','حلويات'],['كيكة تمر',4000,'تمر وهيل وصوص','🍰','حلويات'],['ساندويش حلوم',6500,'حلوم مشوي وخضرة','🥪','فطور'],['توست أفوكادو',7000,'أفوكادو وبيض','🍞','فطور'],['ليمون نعناع',3000,'بارد ومنعش','🍋','بارد'],['ماء',1000,'قنينة 330 مل','💧','بارد']].map((x,i)=>({id:i+1,name:x[0],price:x[1],desc:x[2],icon:x[3],category:x[4]}));
let cart=[],orders=JSON.parse(localStorage.getItem('hillaOrders')||'[]'),customers=JSON.parse(localStorage.getItem('hillaCustomers')||'[{"name":"زينب علي","phone":"٠٧٧٠ ١٢٣ ٤٥٦٧","points":120},{"name":"علي كريم","phone":"٠٧٨١ ٤٥٦ ٨٨٩٩","points":75}]'),currentCustomer=null,category='الكل',orderNum=1048;
const toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)},save=()=>{localStorage.setItem('hillaOrders',JSON.stringify(orders));localStorage.setItem('hillaCustomers',JSON.stringify(customers))},modal=h=>{$('#modalBody').innerHTML=h;$('#modal').showModal()};
function renderProducts(){let q=$('#search').value;let list=products.filter(p=>(category==='الكل'||p.category===category)&&p.name.includes(q));$('#products').innerHTML=list.map(p=>`<button class="product" data-id="${p.id}"><div class="food">${p.icon}</div><div class="product-content"><b>${p.name}</b><small>${p.desc}</small><span class="price">${money(p.price)}</span></div><span class="plus">+</span></button>`).join('')||'<p class="empty">ما لكينا شي بهالاسم</p>';$('#itemCount').textContent=`${list.length} صنف`;$$('.product').forEach(b=>b.onclick=()=>addCart(+b.dataset.id))}
function renderCategories(){let cats=['الكل',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" data-c="${c}">${c}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.c;renderCategories();renderProducts()})}
function addCart(id){let p=products.find(p=>p.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({...p,qty:1});renderCart();toast(`انضاف ${p.name} للسلة`)}
function renderCart(){let sub=cart.reduce((s,p)=>s+p.price*p.qty,0),rate=+$('#serviceRate').value||5,tax=sub*rate/100,total=sub+tax;$('#cartItems').innerHTML=cart.length?cart.map(p=>`<article class="cart-item"><div class="tiny-food">${p.icon}</div><div><b>${p.name}</b><small>${money(p.price)} للواحد</small><div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><span>${p.qty}</span><button data-change="1" data-id="${p.id}">+</button><strong class="line-total">${money(p.price*p.qty)}</strong></div></div></article>`).join(''):'<p class="empty">السلة فارغة، اختار شي من المنيو</p>';$('#subtotal').textContent=money(sub);$('#tax').textContent=money(tax);$('#total').textContent=money(total);$('#payAmount').textContent=cart.length?money(total):'';$('#pay').disabled=!cart.length;$$('[data-change]').forEach(b=>b.onclick=()=>{let x=cart.find(x=>x.id==b.dataset.id);x.qty+=+b.dataset.change;if(x.qty<1)cart=cart.filter(y=>y!==x);renderCart()})}
function showPage(id){$$('.page').forEach(p=>p.classList.remove('shown'));$('#'+id).classList.add('shown');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#pageTitle').textContent={pos:'يلا ناخذ طلب جديد',orders:'طلبات اليوم',menu:'منيو المقهى',customers:'زبائنّا',reports:'أرقام الشفت',settings:'إعدادات المقهى'}[id];if(id==='orders')renderOrders();if(id==='menu')renderManage();if(id==='customers')renderCustomers();if(id==='reports')renderReports();$('.side').classList.remove('open')}
function renderOrders(){let list=[...orders].reverse();$('#ordersList').innerHTML=list.length?list.map(o=>`<article class="order-row"><div><b>${o.no} · ${o.customer||'ضيف'}</b><small>${o.items.map(x=>x.name+' ×'+x.qty).join('، ')}</small></div><b>${money(o.total)}</b><span class="status">مدفوع · ${o.method}</span></article>`).join(''):'<p class="empty">بعد ماكو طلبات مسددة اليوم</p>';$('#orderBadge').textContent=orders.length}
function renderManage(){$('#menuManage').innerHTML=products.map(p=>`<article class="manage-row"><span class="tiny-food">${p.icon}</span><div><b>${p.name}</b><small>${p.category} · ${money(p.price)}</small></div><button data-edit="${p.id}">تعديل السعر</button></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editPrice(+b.dataset.edit))}
function renderCustomers(){$('#customersList').innerHTML=customers.map((c,i)=>`<article class="manage-row"><span class="avatar">${c.name[0]}</span><div><b>${c.name}</b><small>${c.phone} · ${c.points} نقطة</small></div><button data-select="${i}">اختيار</button></article>`).join('');$$('[data-select]').forEach(b=>b.onclick=()=>{currentCustomer=customers[+b.dataset.select];updateCustomer();showPage('pos');toast('تم اختيار الزبون')})}
function renderReports(){let sales=orders.reduce((s,o)=>s+o.total,0);$('#salesStat').textContent=money(sales);$('#ordersStat').textContent=orders.length;$('#avgStat').textContent=money(orders.length?sales/orders.length:0);$('#chart').innerHTML=[34,62,44,88,72,100,57,43].map((v,i)=>`<div class="bar" style="height:${v}%"><small>${8+i}:٠٠</small></div>`).join('')}
function updateCustomer(){$('#customerInitial').textContent=currentCustomer?currentCustomer.name[0]:'+';$('#customerName').textContent=currentCustomer?.name||'إضافة زبون';$('#customerInfo').textContent=currentCustomer?`${currentCustomer.points} نقطة جاهزة إلك`:'حتى نحفظ نقاطه'}
function editPrice(id){let p=products.find(x=>x.id===id);modal(`<h2 class="modal-title">تعديل ${p.name}</h2><label class="modal-field">السعر بالدينار<input id="newPrice" type="number" value="${p.price}"></label><div class="modal-actions"><button class="primary" id="savePrice" type="button">حفظ</button><button class="outline" value="cancel">رجوع</button></div>`);$('#savePrice').onclick=()=>{p.price=+$('#newPrice').value;$('#modal').close();renderProducts();renderManage();toast('تم تحديث السعر')}}
$('#search').oninput=renderProducts;$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#menuToggle').onclick=()=>$('.side').classList.toggle('open');$('#theme').onclick=()=>document.body.classList.toggle('dark');$('#clearCart').onclick=()=>{cart=[];renderCart();toast('تم تفريغ السلة')};$('#newOrder').onclick=()=>{cart=[];currentCustomer=null;orderNum++;$('#orderNo').textContent='#'+orderNum;updateCustomer();renderCart();showPage('pos');toast('طلب جديد جاهز')};$('#customerBtn').onclick=()=>showPage('customers');
$('#addCustom').onclick=()=>{modal(`<h2 class="modal-title">صنف مفتوح</h2><label class="modal-field">الاسم<input id="customName"></label><label class="modal-field">السعر<input id="customPrice" type="number"></label><div class="modal-actions"><button class="primary" id="saveCustom" type="button">إضافة للسلة</button></div>`);$('#saveCustom').onclick=()=>{let n=$('#customName').value,p=+$('#customPrice').value;if(!n||!p)return toast('اكتب الاسم والسعر');cart.push({id:Date.now(),name:n,price:p,qty:1,icon:'✦'});$('#modal').close();renderCart()}};
$('#pay').onclick=()=>{modal(`<h2 class="modal-title">شلون راح يدفع؟</h2><div class="payment-options"><button data-method="كاش">كاش<br><small>دينار عراقي</small></button><button data-method="كي كارد">كي كارد<br><small>بطاقة محلية</small></button><button data-method="فيزا">فيزا / ماستر<br><small>بطاقات</small></button><button data-method="آسياسيل كاش">آسياسيل كاش<br><small>محفظة</small></button></div>`);$$('[data-method]').forEach(b=>b.onclick=()=>complete(b.dataset.method))};function complete(method){let sub=cart.reduce((s,p)=>s+p.price*p.qty,0),total=sub*(1+(+$('#serviceRate').value||5)/100);orders.push({no:'#'+orderNum,customer:currentCustomer?.name,items:cart,total,method});if(currentCustomer)currentCustomer.points+=Math.floor(total/1000);save();$('#modal').close();cart=[];orderNum++;$('#orderNo').textContent='#'+orderNum;renderCart();updateCustomer();toast('تم الدفع، صحة وعافية!')}
$('#addCustomer').onclick=()=>{modal(`<h2 class="modal-title">إضافة زبون</h2><label class="modal-field">الاسم<input id="cName"></label><label class="modal-field">الموبايل<input id="cPhone"></label><div class="modal-actions"><button class="primary" id="saveCustomer" type="button">حفظ</button></div>`);$('#saveCustomer').onclick=()=>{let n=$('#cName').value,p=$('#cPhone').value;if(!n||!p)return toast('أدخل الاسم ورقم الموبايل');customers.push({name:n,phone:p,points:0});save();$('#modal').close();renderCustomers();toast('انضاف الزبون')}};
$('#addMenuItem').onclick=()=>{modal(`<h2 class="modal-title">صنف جديد</h2><label class="modal-field">الاسم<input id="mName"></label><label class="modal-field">السعر<input id="mPrice" type="number"></label><label class="modal-field">القسم<select id="mCat"><option>قهوة</option><option>بارد</option><option>فطور</option><option>حلويات</option></select></label><div class="modal-actions"><button class="primary" id="saveMenu" type="button">إضافة</button></div>`);$('#saveMenu').onclick=()=>{let n=$('#mName').value,p=+$('#mPrice').value;if(!n||!p)return toast('اكتب الاسم والسعر');products.push({id:Date.now(),name:n,price:p,category:$('#mCat').value,desc:'صنف جديد',icon:'☕'});$('#modal').close();renderCategories();renderProducts();renderManage();toast('انضاف الصنف للمنيو')}};
$('#exportOrders').onclick=()=>{let data='رقم الطلب,الزبون,المبلغ,الدفع\n'+orders.map(o=>`${o.no},${o.customer||'ضيف'},${o.total},${o.method}`).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));a.download='طلبات-هلة.csv';a.click();URL.revokeObjectURL(a.href)};$('#saveSettings').onclick=()=>{document.querySelector('.brand span').textContent=$('#cafeName').value;renderCart();toast('تم حفظ الإعدادات')};$('#closeShift').onclick=()=>toast('الشفت بعده مفتوح — كمّل الطلبات وبعدين سكر الحساب');function tick(){$('#clock').textContent=new Date().toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}tick();setInterval(tick,30000);$('#today').textContent='هلا يوسف :'+new Date().toLocaleDateString('ar-IQ',{weekday:'long',day:'numeric',month:'long'});renderCategories();renderProducts();renderCart();renderOrders();

// إضافات التشغيل: لوحة باريستا، مخزون، وإغلاق شفت
const navExtra=document.createElement('div');navExtra.innerHTML='<button class="nav" data-page="barista"><i>◉</i> شاشة الباريستا</button><button class="nav" data-page="inventory"><i>▧</i> المخزون</button><button class="nav" data-page="shifts"><i>◷</i> الشفتات</button>';$('.side nav').insertBefore(navExtra,$('.side nav hr'));
document.querySelector('main').insertAdjacentHTML('beforeend','<section id="barista" class="page"><div class="page-card"><div class="section-heading"><div><p>طلبات حية</p><h2>شاشة الباريستا</h2></div><button class="outline" id="refreshKitchen">تحديث</button></div><div id="kitchenBoard" class="kitchen-board"></div></div></section><section id="inventory" class="page"><div class="page-card"><div class="section-heading"><div><p>المواد الأساسية</p><h2>المخزون والتنبيهات</h2></div><button class="primary" id="addStock">+ إضافة مادة</button></div><div id="stockList" class="manage-list"></div></section><section id="shifts" class="page"><div class="stats"><article><small>بداية الشفت</small><b>٠٨:٠٠</b><span>الكاشير:يوسف</span></article><article><small>كاش الصندوق</small><b id="cashStat">٠ د.ع</b><span>من عمليات الكاش</span></article><article><small>الفرق</small><b>٠ د.ع</b><span>مطابق للحساب</span></article></div><div class="page-card shift-actions"><h2>إدارة الشفت</h2><p>سجّل المبالغ واطبع تقرير الإغلاق من هنا.</p><button class="primary" id="closeShiftReport">إغلاق الشفت وطباعة التقرير</button></div></section>');
let stock=JSON.parse(localStorage.getItem('hillaStock')||'[{"name":"حبوب القهوة","qty":2,"unit":"كغم","min":3},{"name":"حليب كامل الدسم","qty":8,"unit":"لتر","min":5},{"name":"أكواب حجم كبير","qty":22,"unit":"كوب","min":30},{"name":"كرواسون","qty":14,"unit":"قطعة","min":12}]');
function renderKitchen(){let list=[...orders].reverse().slice(0,9);$('#kitchenBoard').innerHTML=list.length?list.map((o,i)=>`<article class="kitchen-ticket"><small>${o.no} · ${o.method}</small><h3>${o.customer||'طلب ضيف'}</h3><p>${o.items.map(x=>x.name+' ×'+x.qty).join(' · ')}</p><button data-ticket="${orders.indexOf(o)}">${o.ready?'تم التسليم':'جاهز للاستلام'}</button></article>`).join(''):'<p class="empty">ماكو طلبات مدفوعة بعد</p>';$$('[data-ticket]').forEach(b=>b.onclick=()=>{orders[+b.dataset.ticket].ready=true;save();renderKitchen();toast('تم تسليم الطلب')})}
function renderStock(){$('#stockList').innerHTML=stock.map((s,i)=>`<article class="manage-row ${s.qty<=s.min?'low-stock':''}"><span class="tiny-food">▧</span><div><b>${s.name}</b><small>${s.qty} ${s.unit} متوفر ${s.qty<=s.min?'· يحتاج طلب':''}</small></div><button data-stock="${i}">تحديث الكمية</button></article>`).join('');$$('[data-stock]').forEach(b=>b.onclick=()=>{let i=+b.dataset.stock,s=stock[i];modal(`<h2 class="modal-title">${s.name}</h2><label class="modal-field">الكمية الحالية<input id="stockQty" type="number" value="${s.qty}"></label><div class="modal-actions"><button class="primary" id="saveStock" type="button">حفظ</button></div>`);$('#saveStock').onclick=()=>{s.qty=+$('#stockQty').value;localStorage.setItem('hillaStock',JSON.stringify(stock));$('#modal').close();renderStock();toast('تم تحديث المخزون')}})}
const baseShow=showPage;showPage=function(id){baseShow(id);let titles={barista:'شاشة الباريستا',inventory:'المخزون والتنبيهات',shifts:'إدارة الشفتات'};if(titles[id])$('#pageTitle').textContent=titles[id];if(id==='barista')renderKitchen();if(id==='inventory')renderStock();if(id==='shifts')$('#cashStat').textContent=money(orders.filter(x=>x.method==='كاش').reduce((s,x)=>s+x.total,0))};
$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#refreshKitchen').onclick=renderKitchen;$('#addStock').onclick=()=>{modal('<h2 class="modal-title">إضافة مادة</h2><label class="modal-field">الاسم<input id="stockName"></label><label class="modal-field">الكمية<input id="stockNewQty" type="number"></label><label class="modal-field">الوحدة<input id="stockUnit" placeholder="كغم / لتر / قطعة"></label><div class="modal-actions"><button class="primary" id="saveNewStock" type="button">إضافة</button></div>');$('#saveNewStock').onclick=()=>{let n=$('#stockName').value,q=+$('#stockNewQty').value,u=$('#stockUnit').value;if(!n||!u)return toast('كمّل المعلومات');stock.push({name:n,qty:q,unit:u,min:5});localStorage.setItem('hillaStock',JSON.stringify(stock));$('#modal').close();renderStock();toast('انضافت المادة')}};$('#closeShiftReport').onclick=()=>{let sales=orders.reduce((s,o)=>s+o.total,0);modal(`<h2 class="modal-title">تقرير إغلاق الشفت</h2><p>عدد الطلبات: <b>${orders.length}</b></p><p>إجمالي المبيعات: <b>${money(sales)}</b></p><p>الكاش: <b>${money(orders.filter(x=>x.method==='كاش').reduce((s,x)=>s+x.total,0))}</b></p><div class="modal-actions"><button class="primary" id="printShift" type="button">طباعة</button></div>`);$('#printShift').onclick=()=>window.print()};

// ===================================================================
// تحديثات جديدة: حذف الأصناف من المنيو + إغلاق الشفت مع مطابقة الكاش
// كل الكود هنا إضافي فقط، ما يمس ولا سطر من الكود الأصلي فوق
// ===================================================================

// --- ١) حذف صنف من المنيو (مو بس تعديل السعر) ---
function renderManage(){$('#menuManage').innerHTML=products.map(p=>`<article class="manage-row"><span class="tiny-food">${p.icon}</span><div><b>${p.name}</b><small>${p.category} · ${money(p.price)}</small></div><div class="row-actions"><button data-edit="${p.id}">تعديل السعر</button><button data-delete="${p.id}" class="danger">حذف</button></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editPrice(+b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>confirmDeleteProduct(+b.dataset.delete))}

function confirmDeleteProduct(id){
  let p=products.find(x=>x.id===id);
  if(!p)return;
  modal(`<h2 class="modal-title">حذف ${p.name}؟</h2><p class="modal-note">هذا الإجراء يشيل الصنف نهائياً من المنيو ومن صفحة الكاشير، وما يرجع الا لو ضفته من جديد.</p><div class="modal-actions"><button class="primary danger-solid" id="confirmDelete" type="button">حذف نهائي</button><button class="outline" value="cancel">رجوع</button></div>`);
  $('#confirmDelete').onclick=()=>{
    products=products.filter(x=>x.id!==id);
    cart=cart.filter(x=>x.id!==id);
    $('#modal').close();
    renderCategories();renderProducts();renderManage();renderCart();
    toast('تم حذف الصنف من المنيو');
  };
}

// --- ٢) إغلاق الشفت: تدخل الكاش الموجود عندك، تضغط طبع، ويحسبلك الفرق ويسكر الحساب ---
function openCloseShiftModal(){
  let cashSales=orders.filter(o=>o.method==='كاش').reduce((s,o)=>s+o.total,0);
  let totalSales=orders.reduce((s,o)=>s+o.total,0);
  modal(`<h2 class="modal-title">إغلاق الشفت</h2><p class="shift-summary-line">الكاش المفروض بالصندوق حسب النظام: <b>${money(cashSales)}</b></p><label class="modal-field">الكاش الموجود عندك فعلياً بالصندوق<input id="actualCash" type="number" placeholder="اكتب المبلغ بالدينار" autofocus></label><p id="cashDiff" class="cash-diff"></p><div class="modal-actions"><button class="primary" id="printCloseShift" type="button">طبع وإغلاق الشفت</button></div>`);
  $('#actualCash').oninput=()=>{
    let raw=$('#actualCash').value,diffEl=$('#cashDiff');
    if(!raw){diffEl.textContent='';diffEl.className='cash-diff';return}
    let actual=+raw,diff=actual-cashSales;
    if(diff===0){diffEl.textContent='مطابق تماماً، ما أكو فرق 👍';diffEl.className='cash-diff ok'}
    else if(diff<0){diffEl.textContent='أكو نقص بالصندوق: '+money(Math.abs(diff));diffEl.className='cash-diff bad'}
    else{diffEl.textContent='أكو زيادة بالصندوق: '+money(diff);diffEl.className='cash-diff good'}
  };
  $('#printCloseShift').onclick=()=>{
    if(!$('#actualCash').value)return toast('اكتب المبلغ الموجود بالصندوق اول');
    let actual=+$('#actualCash').value,diff=actual-cashSales,cafeName=document.querySelector('.brand span').textContent;
    let diffLine=diff===0?'الحساب مطابق تماماً، ما أكو نقص ولا زيادة ✓':diff<0?`أكو نقص بالصندوق قدره ${money(Math.abs(diff))}`:`أكو زيادة بالصندوق قدرها ${money(diff)}`;
    $('#modalBody').innerHTML=`<div class="print-report" id="printArea"><h2 class="modal-title">تقرير إغلاق الشفت</h2><p>${cafeName} · ${new Date().toLocaleString('ar-IQ')}</p><p>عدد الطلبات: <b>${orders.length}</b></p><p>إجمالي المبيعات (كل طرق الدفع): <b>${money(totalSales)}</b></p><p>مبيعات الكاش حسب النظام: <b>${money(cashSales)}</b></p><p>الكاش الفعلي المعدود بالصندوق: <b>${money(actual)}</b></p><p class="diff-line ${diff===0?'ok':diff<0?'bad':'good'}">${diffLine}</p><div class="modal-actions"><button class="primary" id="doPrintShift" type="button">طباعة الآن</button></div></div>`;
    $('#doPrintShift').onclick=()=>{
      window.print();
      let history=JSON.parse(localStorage.getItem('hillaShiftHistory')||'[]');
      history.push({date:new Date().toISOString(),orders:orders.length,sales:totalSales,cashExpected:cashSales,cashActual:actual,diff});
      localStorage.setItem('hillaShiftHistory',JSON.stringify(history));
      orders=[];
      save();
      renderOrders();
      $('#modal').close();
      toast(diff===0?'تم إغلاق الشفت والحساب مطابق تماماً':diff<0?'تم إغلاق الشفت — فيه نقص '+money(Math.abs(diff)):'تم إغلاق الشفت — فيه زيادة '+money(diff));
    };
  };
}
$('#closeShift').title='إغلاق الشفت وطباعة التقرير';
$('#closeShift').onclick=openCloseShiftModal;
$('#closeShiftReport').onclick=openCloseShiftModal;
